### ISSUE TITLE
Search for non-US articles

### ISSUE THREAD

**Issue by Fluxtruth** [pratikpv/google_news_scraper_and_sentiment_analyzer#2]
Hi there,
I have the problem that I have to search for articles that were published in Germany in German. 
The URL ends accordingly: "&hl=de&gl=DE&ceid=DE%3Ade" (DE=Deutschland=Germany, de=deutsch=German)

However, the web scraper searches with the setting "US-en", which means that the articles I am looking for are not saved in the csv.

Is there a way to change that?

**Comment by pratikpv** [comment]
Hi @Fluxtruth 
Sorry for the late reply. I guess by now you would have figured it, but if you or someone else is looking for similar kind of changes then URL variable in google_news_scraper.py needs to be updated according. I would say search manually in chrome browser for news with your region of interest and use that URL in the code. Thats how I did it for region of USA. Also note that cd_min:{min_date},cd_max:{max_date} in the URL needs to be there to select date ranges.
